SiteName = "Class Representatives"
SitePort = "8080"
DevMode = false
UniEmailDomain = "@hw.ac.uk"
EmailAddress = "noreply@example.com"
EmailPassword = "emailpasswordhere"
EmailSMTPServer = "smtp.migadu.com:587"

[DBConfig]
  Type = 1
  Host = "localhost:3306"
  Name = "notes"
  User = "notes"
  Password = "passwordhere"
  Path = "data.db"

[InstanceConfig]
  ShowNotice = true
  NoticeText = "This is an example notice!"
  NoticeLink = "https://example.com"

  [[InstanceConfig.Links]]
    Name = "Example"
    Link = "https://example.com"

  [[InstanceConfig.ClassReps]]
    Name = "Flan bin Flan"
    Email = "flan@example.com"
    Course = "Flani"
